site_name: 📖 MkDocs Site
site_url: https://luckzack.github.io/mkdocs-demo/


repo_url: https://github.com/luckzack/mkdocs-demo/
repo_name: MkDocs Demo
#edit_uri: edit/master/docs/


theme: 
  name: material
  language: en
  highlightjs: true


nav:
  - HOME: 
      - "index.md"
      - About: "./home/about.md"
      - Sponsorship: "./home/sponsorship.md"  